version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: droid-scanner-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: droid-scanner-backend:latest
    container_name: droid-scanner-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/droidsdb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: droid-scanner-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      PORT: 3000
      PROXY_API: http://backend:8080

volumes:
  mongodb_data:
