version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: droid-scanner-mongodb-prod
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: droid-scanner-backend:latest
    container_name: droid-scanner-backend-prod
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/droidsdb
  
  frontend:
      build:
        context: .
        dockerfile: frontend/Dockerfile.prod
      container_name: droid-scanner-frontend-prod
      ports:
        - '5173:80'

volumes:
  mongodb_data:
